### ISSUE TITLE
PGP storage shows public key with 32-bit key ID

### ISSUE THREAD

**Issue by jmkim** [icaros7/icaros7.github.io#1]
Hi,

Your [1] shows your PGP public key with 32-bit key ID. This might be dangerous: see [2].

One of the scenarios, someone generates a PGP key, conflicting with your 32-bit key ID, and upload to the public SKS server. We can get your 32-bit key ID from [1] and retrieve your public key from the public SKS server, using an older version of `gpg`. Then we can retrieve the incorrect key.

For secure, I suggest you update [1] key ID more than 64-bit. I strongly recommend you show us your full key ID.

Thank you.

[1] http://dl.minnote.net/gpg.html
[2] https://evil32.com/

**Comment by icaros7** [comment]
Thank you for your advice. This issue will be open until solve. :)

**Comment by icaros7** [comment]
[icaros7/icaros7.github.io@de49e70](url)

**Comment by icaros7** [comment]
icaros7/icaros7.github.io@de49e7025c71fb920a9cdbf9a822e5d34a4ddd40
